/**
 * Generates docs/product-data-audit.md — a plain report of which catalogue
 * products are missing commercial data (price, url, dimensions).
 *
 * Run: npm run audit:products
 * Never fabricates data; only reports what is present/absent in products.json.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import products from "../data/products.json";

type CatalogueProduct = {
  id: string;
  name: string;
  category: string;
  price: number | null;
  url?: string;
  widthCm?: number | null;
  depthCm?: number | null;
  heightCm?: number | null;
};

const all = products as CatalogueProduct[];

const hasPrice = (p: CatalogueProduct) => typeof p.price === "number";
const hasUrl = (p: CatalogueProduct) => Boolean(p.url && p.url.trim());
const hasDimensions = (p: CatalogueProduct) =>
  Boolean(p.widthCm || p.depthCm || p.heightCm);

const missingPrice = all.filter((p) => !hasPrice(p));
const missingUrl = all.filter((p) => !hasUrl(p));
const missingDimensions = all.filter((p) => !hasDimensions(p));

function pct(count: number) {
  return all.length === 0 ? "0%" : `${Math.round((count / all.length) * 100)}%`;
}

function table(rows: CatalogueProduct[]) {
  if (rows.length === 0) return "_None — all products have this field._\n";

  return [
    "| ID | Name | Category |",
    "| --- | --- | --- |",
    ...rows.map((p) => `| \`${p.id}\` | ${p.name} | ${p.category} |`),
  ].join("\n");
}

const generatedAt = new Date().toISOString().slice(0, 10);

const report = `# Product Data Audit

_Generated by \`npm run audit:products\` on ${generatedAt}. Do not edit by hand._

Total products: **${all.length}**

| Field | Missing | Coverage gap |
| --- | --- | --- |
| price | ${missingPrice.length} / ${all.length} | ${pct(missingPrice.length)} |
| url | ${missingUrl.length} / ${all.length} | ${pct(missingUrl.length)} |
| dimensions | ${missingDimensions.length} / ${all.length} | ${pct(missingDimensions.length)} |

Dimensions = at least one of widthCm / depthCm / heightCm present.

## Products missing price (${missingPrice.length})

${table(missingPrice)}

## Products missing url (${missingUrl.length})

${table(missingUrl)}

## Products missing dimensions (${missingDimensions.length})

${table(missingDimensions)}
`;

const outputPath = join(
  dirname(fileURLToPath(import.meta.url)),
  "../../docs/product-data-audit.md"
);

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, report, "utf8");

console.log(
  `Wrote product data audit: ${outputPath}\n` +
    `  price missing:      ${missingPrice.length}/${all.length}\n` +
    `  url missing:        ${missingUrl.length}/${all.length}\n` +
    `  dimensions missing: ${missingDimensions.length}/${all.length}`
);
